#!/usr/bin/env node
// build.js — Jarvis Vercel build step
// -----------------------------------------------------------------------------
// Reads API keys and VAPID public key from Vercel project environment
// variables and writes ./env.js (loaded via <script src="env.js"> in
// index.html, and consumed at runtime by
// chat.js and the push-subscription flow in stack.html).
//
// Required env vars (set in Vercel → Settings → Environment Variables):
//   - GEMINI_API_KEY       (Gemini AI for food estimation)
//   - GROQ_API_KEY         (Groq fallback for food estimation)
//   - VAPID_PUBLIC_KEY     (VAPID public key for web push; private key
//                           stays server-side only — do NOT commit it)
//
// The build will succeed with empty values (the deploy keeps working — Gemini
// features just degrade gracefully and console.warn a missing-key message) but
// Vercel will print a warning so the misconfiguration is loud in build logs.
// -----------------------------------------------------------------------------

'use strict';

const fs = require('fs');
const path = require('path');

const GEMINI_KEY = process.env.GEMINI_API_KEY || '';
const GROQ_KEY = process.env.GROQ_API_KEY || '';
const VAPID_PUBLIC_KEY = process.env.VAPID_PUBLIC_KEY || '';

if (!GEMINI_KEY) {
  console.warn('[build.js] WARN: GEMINI_API_KEY env var is empty or missing.');
  console.warn('[build.js]        Set it in Vercel → Settings → Environment Variables.');
}
if (!GROQ_KEY) {
  console.warn('[build.js] WARN: GROQ_API_KEY env var is empty or missing.');
  console.warn('[build.js]        Set it in Vercel → Settings → Environment Variables.');
}
if (!VAPID_PUBLIC_KEY) {
  console.warn('[build.js] WARN: VAPID_PUBLIC_KEY env var is empty or missing.');
  console.warn('[build.js]        Set it in Vercel → Settings → Environment Variables. Without it, the "Enable meal reminders" button cannot subscribe to push.');
}

// JSON.stringify handles all escaping (quotes, backslashes, newlines) safely.
const banner =
  '// Auto-generated by build.js at deploy time. Do not edit by hand.\n' +
  '// Source values come from Vercel project env vars.\n';
const body =
  'window.ENV_GEMINI_API_KEY    = ' + JSON.stringify(GEMINI_KEY) + ';\n' +
  'window.ENV_GROQ_API_KEY      = ' + JSON.stringify(GROQ_KEY)   + ';\n' +
  'window.ENV_VAPID_PUBLIC_KEY  = ' + JSON.stringify(VAPID_PUBLIC_KEY) + ';\n';

const outPath = path.join(__dirname, 'env.js');
fs.writeFileSync(outPath, banner + body, 'utf8');

console.log('[build.js] Wrote ' + outPath + ' (GEMINI=' + (GEMINI_KEY ? 'set' : 'empty') + ', GROQ=' + (GROQ_KEY ? 'set' : 'empty') + ', VAPID_PUBLIC=' + (VAPID_PUBLIC_KEY ? 'set' : 'empty') + ').');
