#!/usr/bin/env node
// build.js — Jarvis Vercel build step
// -----------------------------------------------------------------------------
// Reads API keys from Vercel project environment variables and writes ./env.js
// (loaded via <script src="env.js"> in index.html, body.html, soccer.html, and
// consumed at runtime by chat.js).
//
// Required env vars (set in Vercel → Settings → Environment Variables):
//   - GEMINI_API_KEY
//   - GROQ_API_KEY
//
// The build will succeed with empty values (the deploy keeps working — Gemini
// features just degrade gracefully and console.warn a missing-key message) but
// Vercel will print a warning so the misconfiguration is loud in build logs.
// -----------------------------------------------------------------------------

'use strict';

const fs = require('fs');
const path = require('path');

const GEMINI_KEY = process.env.GEMINI_API_KEY || '';
const GROQ_KEY = process.env.GROQ_API_KEY || '';

if (!GEMINI_KEY) {
  console.warn('[build.js] WARN: GEMINI_API_KEY env var is empty or missing.');
  console.warn('[build.js]        Set it in Vercel → Settings → Environment Variables.');
}
if (!GROQ_KEY) {
  console.warn('[build.js] WARN: GROQ_API_KEY env var is empty or missing.');
  console.warn('[build.js]        Set it in Vercel → Settings → Environment Variables.');
}

// JSON.stringify handles all escaping (quotes, backslashes, newlines) safely.
const banner =
  '// Auto-generated by build.js at deploy time. Do not edit by hand.\n' +
  '// Source values come from Vercel project env vars.\n';
const body =
  'window.ENV_GEMINI_API_KEY = ' + JSON.stringify(GEMINI_KEY) + ';\n' +
  'window.ENV_GROQ_API_KEY   = ' + JSON.stringify(GROQ_KEY)   + ';\n';

const outPath = path.join(__dirname, 'env.js');
fs.writeFileSync(outPath, banner + body, 'utf8');

console.log('[build.js] Wrote ' + outPath + ' (GEMINI=' + (GEMINI_KEY ? 'set' : 'empty') + ', GROQ=' + (GROQ_KEY ? 'set' : 'empty') + ').');
