-- ============================================
-- Supabase Setup for Weight Tracker
-- Run this in your Supabase SQL Editor
-- ============================================

-- Create weight_logs table for storing daily weight entries
CREATE TABLE IF NOT EXISTS weight_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date DATE NOT NULL UNIQUE,
  weight DECIMAL(5,2) NOT NULL,
  note TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create progress_photos table for storing photo metadata
CREATE TABLE IF NOT EXISTS progress_photos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date DATE NOT NULL,
  weight DECIMAL(5,2) NOT NULL,
  storage_path TEXT NOT NULL UNIQUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create updated_at trigger function
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Add updated_at trigger to weight_logs
CREATE TRIGGER update_weight_logs_updated_at
  BEFORE UPDATE ON weight_logs
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- Enable Row Level Security (RLS)
ALTER TABLE weight_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE progress_photos ENABLE ROW LEVEL SECURITY;

-- Create policies for weight_logs (allow all operations for authenticated users)
CREATE POLICY "Users can view all weight logs"
  ON weight_logs FOR SELECT
  USING (auth.role() = 'authenticated');

CREATE POLICY "Users can insert weight logs"
  ON weight_logs FOR INSERT
  WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Users can update weight logs"
  ON weight_logs FOR UPDATE
  USING (auth.role() = 'authenticated');

CREATE POLICY "Users can delete weight logs"
  ON weight_logs FOR DELETE
  USING (auth.role() = 'authenticated');

-- Create policies for progress_photos (allow all operations for authenticated users)
CREATE POLICY "Users can view all progress photos"
  ON progress_photos FOR SELECT
  USING (auth.role() = 'authenticated');

CREATE POLICY "Users can insert progress photos"
  ON progress_photos FOR INSERT
  WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Users can delete progress photos"
  ON progress_photos FOR DELETE
  USING (auth.role() = 'authenticated');

-- ============================================
-- Storage Setup Instructions
-- ============================================
-- 1. Go to your Supabase project dashboard
-- 2. Navigate to Storage on the left sidebar
-- 3. Click "Create a new bucket"
-- 4. Name the bucket: progress-photos
-- 5. Make it Public bucket: NO (keep it private)
-- 6. Click "Create bucket"
-- 
-- 7. After creating the bucket, click on it
-- 8. Go to Policies tab
-- 9. Click "New Policy"
-- 10. Select "For full customization" or use these presets:
-- 
-- Policy for uploading:
-- CREATE POLICY "Users can upload photos"
-- ON storage.objects FOR INSERT
-- TO authenticated
-- WITH CHECK (bucket_id = 'progress-photos');
-- 
-- Policy for viewing:
-- CREATE POLICY "Users can view photos"
-- ON storage.objects FOR SELECT
-- TO authenticated
-- USING (bucket_id = 'progress-photos');
-- 
-- Policy for deleting:
-- CREATE POLICY "Users can delete photos"
-- ON storage.objects FOR DELETE
-- TO authenticated
-- USING (bucket_id = 'progress-photos');
